
export type KnowledgeModule = {
  id: string;
  category: string;
  title: string;
  summary: string;
  details: string;
};

export const KNOWLEDGE_HUB: KnowledgeModule[] = [
  { id: "1", category: "Aqidah", title: "Tawhid Al-Uluhiyyah", summary: "The oneness of worship.", details: "This is the belief that Allah alone is the only one worthy of worship, and all acts of worship must be directed to Him alone." },
  { id: "2", category: "Aqidah", title: "Tawhid Al-Rububiyyah", summary: "The oneness of Lordship.", details: "Believing that Allah is the sole Creator, Provider, and Sustainer of the entire universe." },
  { id: "3", category: "Aqidah", title: "Tawhid Al-Asma wa-Sifat", summary: "The oneness of Names and Attributes.", details: "Affirming the names and attributes of Allah as mentioned in the Quran and Sunnah without distortion, denial, or anthropomorphism." },
  { id: "4", category: "Aqidah", title: "Pillars of Iman", summary: "The six articles of faith.", details: "Belief in Allah, His Angels, His Books, His Messengers, the Last Day, and Qadar (Divine Decree)." },
  { id: "5", category: "Practices", title: "Pillars of Islam", summary: "The five foundations of practice.", details: "Shahadah, Salah, Zakat, Sawm (Fasting), and Hajj." },
  { id: "6", category: "Practices", title: "Conditions of Salah", summary: "Requirements before prayer.", details: "Islam, Sanity, Maturity, Removal of Impurity, Wudu, Covering Awrah, Facing Qibla, Intention, and Time." },
  { id: "7", category: "Practices", title: "Nullifiers of Wudu", summary: "What breaks ritual purity.", details: "Bodily discharges, deep sleep, loss of consciousness, touching private parts directly, and eating camel meat (according to some scholars)." },
  { id: "8", category: "History", title: "Biography: Abu Bakr", summary: "The First Caliph.", details: "Known as As-Siddiq, he was the closest companion of the Prophet and the first man to embrace Islam." },
  { id: "9", category: "History", title: "Biography: Umar ibn Al-Khattab", summary: "The Second Caliph.", details: "Known as Al-Faruq (The Distinguisher), he was famous for his justice and strength." },
  { id: "10", category: "History", title: "Biography: Uthman ibn Affan", summary: "The Third Caliph.", details: "Known as Dhun-Nurayn (Owner of Two Lights), he was famous for his modesty and generosity." },
  { id: "11", category: "History", title: "Biography: Ali ibn Abi Talib", summary: "The Fourth Caliph.", details: "The cousin and son-in-law of the Prophet, known for his bravery and wisdom." },
  { id: "12", category: "History", title: "Battle of Badr", summary: "The first major battle.", details: "Occurred in 2 AH, where a small Muslim force defeated a much larger Meccan army through divine aid." },
  { id: "13", category: "Hadith", title: "The 40 Hadith of Nawawi", summary: "Essential Prophetic sayings.", details: "A collection that encompasses the foundations of the Islamic religion." },
  { id: "14", category: "Ethics", title: "Rights of Parents", summary: "Highest duty after worship.", details: "Obedience, kindness, and financial support are mandatory unless they command disobedience to Allah." },
  { id: "15", category: "Ethics", title: "Rights of Neighbors", summary: "Treatment of those nearby.", details: "The Prophet emphasized the rights of neighbors so much that companions thought they might inherit wealth." },
  { id: "16", category: "Eschatology", title: "Minor Signs of the Hour", summary: "Precursors to the End Times.", details: "Includes the loss of honesty, the spread of ignorance, and buildings becoming taller." },
  { id: "17", category: "Eschatology", title: "Major Signs of the Hour", summary: "Proximate signs of the End.", details: "The Dajjal, the descent of Isa (Jesus), Gog and Magog, and the sun rising from the west." },
  { id: "18", category: "Finance", title: "Usury (Riba)", summary: "The prohibition of interest.", details: "Riba is strictly forbidden as it causes oppression and destroys the economic balance." },
  { id: "19", category: "Family", title: "Raising Children", summary: "Nurturing the next generation.", details: "Parents are responsible for teaching their children the creed and character of Islam from a young age." },
  { id: "20", category: "Methodology", title: "The Concept of Bid'ah", summary: "Innovation in religion.", details: "Introducing new practices into the religion that have no basis in the Quran or Sunnah." },
  { id: "21", category: "Theology", title: "Names of Allah", summary: "Understanding the Creator.", details: "Learning the 99 names of Allah is a means to enter Paradise and understand His perfection." },
  { id: "22", category: "Theology", title: "Attributes of Allah", summary: "Divine characteristics.", details: "Affirming what Allah has affirmed for Himself without resembling His creation." },
  { id: "23", category: "Eschatology", title: "Description of Jannah", summary: "The eternal reward.", details: "A place with rivers of milk, honey, and wine, where there is no pain, sadness, or death." },
  { id: "24", category: "Eschatology", title: "Description of Jahannam", summary: "The place of punishment.", details: "A place of fire and intense cold for those who rejected the message of the Messengers." },
  { id: "25", category: "Etiquette", title: "Manners of Knowledge", summary: "Seeking sacred wisdom.", details: "Patience, sincerity (Ikhlas), and acting upon what is learned are the keys to knowledge." },
  { id: "26", category: "Etiquette", title: "Etiquettes of Dua", summary: "Calling upon Allah.", details: "Facing the Qibla, raising hands, and starting with praise for Allah and blessings on the Prophet." },
  { id: "27", category: "Spirituality", title: "Repentance (Tawbah)", summary: "Turning back to Allah.", details: "Requires stopping the sin, regretting it, and resolving never to return to it." },
  { id: "28", category: "Health", title: "Ruqyah Shariah", summary: "Spiritual healing.", details: "Using the Quran and authentic Duas to seek protection from the evil eye, magic, and illness." },
  { id: "29", category: "Law", title: "Islamic Finance", summary: "Ethical transactions.", details: "Trade is permissible while interest is forbidden, focusing on risk-sharing and tangible assets." },
  { id: "30", category: "Law", title: "Inheritance (Mirath)", summary: "Division of wealth.", details: "Precisely defined in the Quran to ensure justice among family members after death." },
  { id: "31", category: "Practices", title: "Friday Prayer (Jumu'ah)", summary: "The weekly assembly.", details: "Mandatory for men, involving two units of prayer and a sermon (Khutbah)." },
  { id: "32", category: "Practices", title: "Eid Al-Fitr", summary: "Festival of Fast-breaking.", details: "Celebrated after Ramadan to thank Allah for the strength to fast." },
  { id: "33", category: "Practices", title: "Eid Al-Adha", summary: "Festival of Sacrifice.", details: "Commemorates the sacrifice of Ibrahim (Abraham) and coincides with the Hajj pilgrimage." },
  { id: "34", category: "Ethics", title: "Modesty (Haya)", summary: "A branch of faith.", details: "Modesty in speech, dress, and behavior is central to the Muslim identity." },
  { id: "35", category: "Society", title: "Ethics of Da'wah", summary: "Inviting to Islam.", details: "Must be done with wisdom, good speech, and patience, as demonstrated by the Prophets." },
  { id: "36", category: "Theology", title: "Divine Decree (Qadar)", summary: "Faith in destiny.", details: "Everything happens by the knowledge, will, and creation of Allah." },
  { id: "37", category: "History", title: "Conquest of Makkah", summary: "The ultimate victory.", details: "The Prophet returned to Makkah peacefully, breaking the idols and forgiving his enemies." },
  { id: "38", category: "History", title: "The 10 Promised Jannah", summary: "Elite companions.", details: "Ten companions whom the Prophet explicitly named as residents of Paradise." },
  { id: "39", category: "Hadith", title: "Sahih Al-Bukhari", summary: "The most authentic book.", details: "The first collection to focus solely on authentic (Sahih) narrations." },
  { id: "40", category: "Hadith", title: "Sahih Muslim", summary: "The second most authentic.", details: "Famous for its excellent arrangement and rigorous conditions for narrators." },
  { id: "41", category: "Aqidah", title: "Meaning of Shahadah", summary: "The key to Islam.", details: "Negating all false gods and affirming that none is worthy of worship except Allah." },
  { id: "42", category: "Family", title: "Rights of Spouses", summary: "Mutual mercy and love.", details: "Islam defines roles for both husband and wife to ensure a stable and loving family unit." },
  { id: "43", category: "Ethics", title: "Kindness to Animals", summary: "Mercy to all creation.", details: "The Prophet mentioned rewards for being kind to animals and punishment for cruelty." },
  { id: "44", category: "Spirituality", title: "Night Prayer (Tahajjud)", summary: "Voluntary night worship.", details: "The most virtuous prayer after the obligatory ones, performed in the last third of the night." },
  { id: "45", category: "Eschatology", title: "The Bridge (Sirat)", summary: "Crossing over Hell.", details: "A bridge over the fire that everyone must cross, its speed depends on one's deeds." },
  { id: "46", category: "Eschatology", title: "The Basin (Hawd)", summary: "The Prophet's fountain.", details: "A place where believers will drink from the Prophet's hand and never thirst again." },
  { id: "47", category: "Society", title: "Truthfulness (Sidq)", summary: "A core virtue.", details: "The Prophet was known as Al-Amin (the trustworthy) even before his prophethood." },
  { id: "48", category: "Spirituality", title: "Sincerity (Ikhlas)", summary: "Purity of intention.", details: "Doing acts of worship solely for the sake of Allah, without seeking fame or praise." },
  { id: "49", category: "History", title: "Battle of Uhud", summary: "A lesson in obedience.", details: "Where Muslims faced a setback due to some archers leaving their posts against orders." },
  { id: "50", category: "Practices", title: "Traveler's Prayer", summary: "Shortening Salah.", details: "A concession from Allah to shorten and combine prayers while traveling." },
  { id: "51", category: "Food", title: "Halal vs Haram", summary: "Dietary laws.", details: "Prohibiting pork, intoxicants, and meat not slaughtered according to Islamic law." },
  { id: "52", category: "Methodology", title: "Following the Salaf", summary: "Correct understanding.", details: "Understanding the Quran and Sunnah as the companions and the first three generations did." },
  { id: "53", category: "Law", title: "Conditions of Zakat", summary: "Obligatory charity.", details: "Paid on wealth that has reached the Nisab (threshold) and been held for a lunar year." },
  { id: "54", category: "Law", title: "Conditions of Fasting", summary: "Ramadan requirements.", details: "Intention, refraining from food/drink/intercourse from dawn until sunset." },
  { id: "55", category: "Society", title: "Avoiding Backbiting", summary: "Protecting honor.", details: "The Prophet likened backbiting to eating the flesh of one's dead brother." },
  { id: "56", category: "Ethics", title: "Patience (Sabr)", summary: "Enduring with hope.", details: "Three types: patience in obeying Allah, patience in avoiding sin, and patience in trials." },
  { id: "57", category: "Ethics", title: "Gratitude (Shukr)", summary: "Thanking the Provider.", details: "Allah promises to increase the blessings of those who are grateful." },
  { id: "58", category: "History", title: "The Hijrah", summary: "The migration to Madinah.", details: "The turning point that marked the start of the Islamic calendar and the first Islamic state." },
  { id: "59", category: "Spirituality", title: "Remembrance (Dhikr)", summary: "Keeping the heart alive.", details: "The difference between one who remembers Allah and one who doesn't is like the living and the dead." },
  { id: "60", category: "Aqidah", title: "Intercession (Shafa'ah)", summary: "Mediation on Judgment Day.", details: "The Prophet will be granted the Great Intercession to start the account for all mankind." }
];
